import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "secondary": "#7c5800",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#72fe88",
        "surface-container": "#edeeef",
        "outline": "#717970",
        "on-secondary-container": "#6b4b00",
        "on-primary-container": "#73ad7b",
        "primary-fixed": "#b4f1bb",
        "secondary-fixed": "#ffdea8",
        "tertiary-fixed-dim": "#53e16f",
        "surface": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "on-tertiary-container": "#1ab74c",
        "primary-container": "#00401a",
        "primary": "#00280e",
        "tertiary": "#002809",
        "on-surface-variant": "#414940",
        "on-secondary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#00531c",
        "inverse-primary": "#99d5a0",
        "tertiary-container": "#004014",
        "inverse-on-surface": "#f0f1f2",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#00210a",
        "background": "#f8f9fa",
        "on-surface": "#191c1d",
        "surface-bright": "#f8f9fa",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#002107",
        "surface-container-highest": "#e1e3e4",
        "on-primary": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffba20",
        "primary-fixed-dim": "#99d5a0",
        "on-primary-fixed-variant": "#175129",
        "surface-tint": "#326a3f",
        "on-secondary-fixed-variant": "#5e4200",
        "secondary-container": "#feb700",
        "outline-variant": "#c0c9be",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
